<?php
return array( 
	"SITE_URL" 					=> "http://localhost/alignya_laravel/",
	"SITE_TITLE" 				=> "Alignya",
	"SITE_EMAIL" 				=> "noreply@chameleon.love",
	'SITE_MODE'					=> "live", //change "local" to "live" on server
	"USER_ROLES" 				=> array(1=>'Admin', 2=>'Users'),
	"ROLE_URLS" 				=> array(1=>'admins', 2=>'users'),
	"PAGINATION" 				=> 10,
	"PAGINATION_COMMENTS" 		=> 3,
	"PAGINATION_FOLLOWERS" 		=> 9,
	"FRONT_PAGINATION" 			=> 10,
	"PAGINATION_NOTIFICATION"   => 20,
	"PAGINATION_GROUPS"   		=> 20,
	"YES_NO" 					=> array(1=>'Yes', 0=>'No'),
	"GENDER" 					=> array(1=>'Male',  2=>'Female'),
	"STATUS" 					=> array(1=>'Active', 0=>'Inactive'),
	"USER_THUMB_WIDTH"			=> 60,
	"USER_MEDIUM_WIDTH"			=> 124,
	"TAX_PER"					=> 0,
	'ADMIN_SITE_PRFIX'			=> "13061603",
	'EMBED_DOMAIN'				=> "streamer.studio",
	"COPYRIGHT_MESSAGE" 		=> "2020 Alignya - All rights reserved.",
	"GROUPPRIVACY" 				=> array(1=>'Public',  2=>'Private', '3' => 'On Invitation'),
	"LEVELS" 					=> array(1=>'Level 1', 2=>'Level 2', 3=>'Level 3'),
	"SiteValue" 				=> array('paypal_mode'=>'sandbox', 'paypal_api_username'=>'gaurav2212016-facilitator_api1.outlook.com','paypal_api_password'=>'FWLUFB9PHDMB8FEK','paypal_api_signature'=>'ABhCI5kfIeM7nPsgeZJqsnMV8P31A4uQZkk.5ga1YIzaRNeUXsTUjdYJ'),
	"Quarter" => array(0=>'FULL',1=>'Q1',2=>'Q2',3=>'Q3',4=>'Q4',5=>'H1',6=>'H2'),
	"PAGE_PRODUCT_ID" 			=> "prod_DeLuHBDVQAx40r",
	"PLAN_PERIOD" => array(1=>'Monthly',2=>'Yearly'),
	"COMPANY_FISCAL_MONTH" => array(1=>"January",2=>"February",3=>"March",4=>"April",5=>"May",6=>"June",7=>"July",8=>"Auguest",9=>"September",10=>"October",11=>"November",12=>"December"),
);